### ISSUE TITLE
Create a barebones extension to build on

### ISSUE THREAD

**Issue by Michael-Overall** [PopeSpaceous/CodeTalker#2]
Try following [this tutorial](https://code.visualstudio.com/docs/extensions/example-hello-world) to get a basic extension up that we can start hacking on.

Also see [this link](https://code.visualstudio.com/docs/extensions/overview) for VS Code's overview of extensions

**Comment by steaward** [comment]
I can get this done! 

I think whomever has claimed interest in this project in our OSD class, should read up here: 
https://code.visualstudio.com/docs/extensions/publish-extension

So that we can all publish changes as they happen :)

**Comment by PopeSpaceous** [comment]
I've merged this from PR #6 . 

I'll update your instructions to add to the readme.
Thanks for your work!
