### ISSUE TITLE
Set up a Communications Channel

### ISSUE THREAD

**Issue by PopeSpaceous** [PopeSpaceous/CodeTalker#3]
Either Set up a Slack or Discord channel for communication.
I know Discord has screen sharing in it.

**Comment by deepanjali19** [comment]
I would create a Slack channel for communication.

I am selecting Slack as many Seneca students especially from DPS 909 are already aware of the platform.

I will add the link here as well as in the README file.

**Comment by deepanjali19** [comment]
Here is the link to the Slack group:

Slack for [CodeTalker](https://join.slack.com/t/codetalkerworkspace/shared_invite/enQtNDcyMjQ4MjYzNzMwLTYzMjM4MDUwMzAzYTc1MjBhNDNjZWM5MGU5Y2FkODUzMWZjM2M4NjJlZGZkYjIwNTNlYzM1NGQxOGYzNDUyOTY)

**Comment by PopeSpaceous** [comment]
Can you please add that link to the README.md Thanks :)

**Comment by PopeSpaceous** [comment]
Thanks for the setup! 👍
